version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - AnthonyPorthouse

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - AnthonyPorthouse

    groups:
      tanstack-router:
        patterns:
          - "@tanstack/react-router"
          - "@tanstack/router-*"
      tanstack-query:
        patterns:
          - "@tanstacl/react-query*"
      types:
        patterns:
          - "@types/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@tanstack/eslint-plugin-query"
      vite:
        patterns:
          - "vite"
          - "vite-*"
          - "@vitejs/*"
          - "*-vite-plugin"
