name: "CI"

on: ["pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install Node Dependencies
        run: npm ci
      - name: Check Formatting
        run: npx prettier --check .
      - name: Build Project
        run: npm run build
