name: "CI"

on: ["pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [latest]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: Install Node Dependencies
        run: npm ci
      - name: Check Formatting
        run: npx prettier --check .
      - name: Build Project
        run: npm run build

  sbom:
    name: SBOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: anchore/sbom-action@v0

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
      - name: Install Node Dependencies
        run: npm ci
      - name: Run Coverage Report
        run: npm run coverage
      - uses: actions/upload-artifact@v5
        with:
          name: coverage
          path: coverage/

      - name: Run Mutation Tests
        run: npm run test:mutation
      - uses: actions/upload-artifact@v5
        with:
          name: reports
          path: reports/

  sonarcloud:
    name: SonarCloud
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v5
        with:
          name: coverage
          path: coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
