name: "CI"

on: ["pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install Node Dependencies
        run: npm ci
      - name: Check Formatting
        run: npx prettier --check .
      - name: Build Project
        run: npm run build

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Node Dependencies
        run: npm ci
      - name: Run Coverage Report
        run: npm run coverage
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  sonarcloud:
    name: SonarCloud
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: coverage

      - name: show files
        run: ls -1

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
