name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag: ${{ steps.release.outputs.tag_name}}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

  release-to-cloudflare:
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/release-to-cloudflare.yaml
    with:
      tag: ${{ needs.release-please.outputs.tag }}
    secrets: inherit
